### ISSUE TITLE
Set slider value by clicking the text next to the slider

### ISSUE THREAD

**Issue by TetteDev** [MasterP-kr/CanvasGUI#2]
https://i.imgur.com/Zv9PZlH.png
![alt text](https://i.imgur.com/Zv9PZlH.png "Suggestion")

Clicking within the area of the green boxes, would allow the user to type in a value manually, instead of having to carefully drag the slider (this can be annoying when the ranges are huge etc)

**Comment by MasterP-kr** [comment]
Check v0.6 For slider with slider with input.
